=== dnd-mdn/mobile/json/config.schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "CAF Mobile App configuration",
    "description": "Defines API and asset locations as well as the home tab configuration.",
    "type": "object",
    "properties": {
        "latest_app_version": {
            "description": "The latest version of the app. Used to determine if a new version is available.",
            "type": "string",
            "pattern": "^\\d+\\.\\d+\\.\\d+$"
        },
        "apiServer": {
            "description": "The base URL of the API.",
            "type": "string",
            "format": "uri"
        },
        "canforgens": {
            "description": "The base URL of the CANFORGENS API.",
            "type": "object",
            "properties": {
                "ip": {
                    "type": "string",
                    "format": "uri"
                }
            },
            "required": [
                "ip"
            ]
        },
        "resources": {
            "description": "The URL of the resources data",
            "type": "object",
            "properties": {
                "ip": {
                    "type": "string",
                    "format": "uri"
                },
                "path": {
                    "type": "string",
                    "format": "uri-reference"
                }
            },
            "required": [
                "ip",
                "path"
            ]
        },
        "subscriptions": {
            "description": "The URL of the social media account data.  No longer in use.",
            "type": "object",
            "properties": {
                "ip": {
                    "type": "string",
                    "format": "uri"
                },
                "path": {
                    "type": "string",
                    "format": "uri-reference"
                }
            },
            "required": [
                "ip",
                "path"
            ]
        },
        "feedbackForm": {
            "description": "Localized URL of the feedback form.",
            "type": "object",
            "properties": {
                "web": {
                    "type": "object",
                    "properties": {
                        "en": {
                            "type": "string",
                            "format": "uri"
                        },
                        "fr": {
                            "type": "string",
                            "format": "uri"
                        }
                    },
                    "required": [
                        "en",
                        "fr"
                    ]
                }
            },
            "required": [
                "web"
            ]
        },
        "appStore": {
            "description": "Localized App store URLs.",
            "type": "object",
            "properties": {
                "android": {
                    "descrption": "Android app store URL.",
                    "type": "object",
                    "properties": {
                        "en": {
                            "type": "string",
                            "format": "uri"
                        },
                        "fr": {
                            "type": "string",
                            "format": "uri"
                        }
                    },
                    "required": [
                        "en",
                        "fr"
                    ]
                },
                "ios": {
                    "descrption": "IOS app store URL.",
                    "type": "object",
                    "properties": {
                        "en": {
                            "type": "string",
                            "format": "uri"
                        },
                        "fr": {
                            "type": "string",
                            "format": "uri"
                        }
                    },
                    "required": [
                        "en",
                        "fr"
                    ]
                }
            },
            "required": [
                "android",
                "ios"
            ]
        },
        "homeTab": {
            "description": "The home tab configuration.",
            "type": "object",
            "properties": {
                "backgroundImages": {
                    "description": "List of URLs of background images.",
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "url": {
                                "type": "string",
                                "format": "uri"
                            }
                        },
                        "required": [
                            "url"
                        ]
                    }
                },
                "featuredNews": {
                    "description": "Configure the featured news element.",
                    "type": "object",
                    "properties": {
                        "published": {
                            "description": "If false, it will default to displaying the latest news item.",
                            "type": "boolean"
                        },
                        "size": {
                            "description": "The grid size of the element. 12 is full width.",
                            "type": "string",
                            "pattern": "^\\d+$"
                        },
                        "id": {
                            "description": "The postID of the post to feature.",
                            "type": "string",
                            "pattern": "^\\d+$"
                        }
                    },
                    "required": [
                        "published",
                        "size",
                        "id"
                    ]
                },
                "alerts": {
                    "description": "Red high priority buttons on the home tab.",
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "published": {
                                "description": "If false, it will not display the button.",
                                "type": "boolean"
                            },
                            "size": {
                                "description": "The grid size of the element. 12 is full width.",
                                "type": "string",
                                "pattern": "^\\d+$"
                            },
                            "en": {
                                "type": "object",
                                "properties": {
                                    "name": {
                                        "description": "The text of the button.",
                                        "type": "string"
                                    },
                                    "url": {
                                        "type": "string",
                                        "format": "uri-reference"
                                    }
                                },
                                "required": [
                                    "name",
                                    "url"
                                ]
                            },
                            "fr": {
                                "type": "object",
                                "properties": {
                                    "name": {
                                        "description": "The text of the button.",
                                        "type": "string"
                                    },
                                    "url": {
                                        "type": "string",
                                        "format": "uri-reference"
                                    }
                                },
                                "required": [
                                    "name",
                                    "url"
                                ]
                            }
                        },
                        "required": [
                            "published",
                            "size",
                            "en",
                            "fr"
                        ]
                    }
                },
                "buttons": {
                    "description": "Buttons for the home tab.",
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "published": {
                                "description": "If false, it will not display the button.",
                                "type": "boolean"
                            },
                            "size": {
                                "description": "The grid size of the element. 12 is full width.",
                                "type": "string",
                                "pattern": "^\\d+$"
                            },
                            "en": {
                                "type": "object",
                                "properties": {
                                    "name": {
                                        "description": "The text of the button.",
                                        "type": "string"
                                    },
                                    "url": {
                                        "type": "string",
                                        "format": "uri-reference"
                                    }
                                },
                                "required": [
                                    "name",
                                    "url"
                                ]
                            },
                            "fr": {
                                "type": "object",
                                "properties": {
                                    "name": {
                                        "description": "The text of the button.",
                                        "type": "string"
                                    },
                                    "url": {
                                        "type": "string",
                                        "format": "uri-reference"
                                    }
                                },
                                "required": [
                                    "name",
                                    "url"
                                ]
                            }
                        },
                        "required": [
                            "published",
                            "size",
                            "en",
                            "fr"
                        ]
                    }
                }
            },
            "required": [
                "backgroundImages",
                "featuredNews",
                "alerts",
                "buttons"
            ]
        }
    },
    "required": [
        "latest_app_version",
        "apiServer",
        "canforgens",
        "resources",
        "subscriptions",
        "feedbackForm",
        "appStore",
        "homeTab"
    ]
}

=== dnd-mdn/mobile/json/config.json
{
    "$schema": "../schema/config.schema.json",
    "latest_app_version": "3.2.0",
    "apiServer": "https://mobile.caf-fac.ca/api/v4",
    "canforgens": {
        "ip": "https://mobile.caf-fac.ca"
    },
    "resources": {
        "ip": "https://www.canada.ca",
        "path": "/content/dam/dnd-mdn/documents/json/mobile/resources.json"
    },
    "subscriptions": {
        "ip": "https://www.canada.ca",
        "path": "/content/dam/dnd-mdn/documents/json/mobile/caf-subscriptions.json"
    },
    "feedbackForm": {
        "web": {
            "en": "https://apps.forces.gc.ca/en/mobile/feedback.asp",
            "fr": "https://apps.forces.gc.ca/fr/mobile/retroaction.asp"
        }
    },
    "appStore": {
        "android": {
            "en": "https://play.google.com/store/apps/details?id=ca.forces.dnd.caf",
            "fr": "https://play.google.com/store/apps/details?id=ca.forces.dnd.caf&hl=fr"
        },
        "ios": {
            "en": "https://apps.apple.com/us/app/canadian-forces/id1125442156",
            "fr": "https://apps.apple.com/fr/app/canadian-forces/id1125442156"
        }
    },
    "homeTab": {
        "backgroundImages": [
            {
                "url": "https://www.canada.ca/content/dam/dnd-mdn/images/mobile-apps/caf-mobile-app/backgrounds/1.jpg"
            },
            {
                "url": "https://www.canada.ca/content/dam/dnd-mdn/images/mobile-apps/caf-mobile-app/backgrounds/2.jpg"
            },
            {
                "url": "https://www.canada.ca/content/dam/dnd-mdn/images/mobile-apps/caf-mobile-app/backgrounds/3.jpg"
            }
        ],
        "featuredNews": {
            "published": false,
            "size": "12",
            "id": "28797"
        },
        "alerts": [
            {
                "published": false,
                "size": "12",
                "en": {
                    "name": "App not available on GC-WiFi",
                    "url": "/tabs/tab-voice"
                },
                "fr": {
                    "name": "App inaccessible sur GC-WIFI",
                    "url": "/tabs/tab-voice"
                }
            }
        ],
        "buttons": [
            {
                "published": false,
                "size": "6",
                "en": {
                    "name": "Latest CANFORGEN",
                    "url": "/canforgens-detail/142-20_e"
                },
                "fr": {
                    "name": "Derniers CANFORGEN",
                    "url": "/canforgens-detail/142-20_f"
                }
            },
            {
                "published": true,
                "size": "6",
                "en": {
                    "name": "Contact us",
                    "url": "/resource-detail",
                    "params": {
                        "n": "21"
                    }
                },
                "fr": {
                    "name": "Contactez-nous",
                    "url": "/resource-detail",
                    "params": {
                        "n": "21"
                    }
                }
            },
            {
                "published": true,
                "size": "6",
                "en": {
                    "name": "Canforgens",
                    "url": "/tabs/tab-canforgens"
                },
                "fr": {
                    "name": "Canforgens",
                    "url": "/tabs/tab-canforgens"
                }
            },
            {
                "published": true,
                "size": "6",
                "en": {
                    "name": "Resources",
                    "url": "/tabs/tab-resources"
                },
                "fr": {
                    "name": "Ressources",
                    "url": "/tabs/tab-resources"
                }
            },
            {
                "published": false,
                "size": "6",
                "en": {
                    "name": "Covid-19",
                    "url": "/resource-detail",
                    "params": {
                        "n": "3"
                    }
                },
                "fr": {
                    "name": "Covid-19",
                    "url": "/resource-detail",
                    "params": {
                        "n": "3"
                    }
                }
            },
            {
                "published": true,
                "size": "6",
                "en": {
                    "name": "Maple Leaf",
                    "url": "https://www.canada.ca/en/department-national-defence/maple-leaf.html?utm_campaign=dnd-mdn-mobile-app-22-23&utm_medium=ma&utm_source=cafapp&utm_content=homepage-en",
                    "params": {
                        "type": "web"
                    }
                },
                "fr": {
                    "name": "Feuille d'érable",
                    "url": "https://www.canada.ca/fr/ministere-defense-nationale/feuille-derable.html?utm_campaign=dnd-mdn-mobile-app-22-23&utm_medium=ma&utm_source=cafapp&utm_content=homepage-fr",
                    "params": {
                        "type": "web"
                    }
                }
            },
            {
                "published": true,
                "size": "12",
                "en": {
                    "name": "OP Unified Recruiter Aide-Mémoire",
                    "url": "https://www.canada.ca/en/department-national-defence/campaigns/get-involved-caf-recruitment/recruiting-aide-memoire.html",
                    "params": {
                        "type": "web"
                    }
                },
                "fr": {
                    "name": "Aide-mémoire sur le recrutement",
                    "url": "https://www.canada.ca/fr/ministere-defense-nationale/campagnes/impliquez-vous-recrutement-fac/aide-memoire-sur-le-recrutement.html",
                    "params": {
                        "type": "web"
                    }
                }
            }
        ]
    }
}
